# AI 프로그래밍 과제 2

In [1]:
import numpy as np

# 문제 1 (4 points)

In [2]:
array_a = np.arange(0,100)
print(array_a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


NumPy의 np.sum()함수를 이용하여 배열안에 모든 원소들의 합을 구함.

In [3]:
sum_array = np.sum(array_a)
print("Sum of all elements in array_a: ", sum_array)

Sum of all elements in array_a:  4950


NumPy의 array_a 배열을 Python의 기본 list_a 리스트로 변환

In [4]:
list_a = array_a.tolist()
print(list_a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


## 프로그래밍 문제 1-1: Python의 리스트 list_a 를 이용하여 np.sum(array_a)과 같은 계산을 수행하는 total_sum() 함수를 작성하시오.

In [5]:
"""
이 셀 안에 코드를 작성하시오.
"""
# 함수 작성
def total_sum(a):
    result = 0
    for i in a:
        result+=i
    return result

위에 구현한 total_sum() 함수를 호출하여 반환된 결과값(sum_list)을 출력함.

In [6]:
# 함수 호출
sum_list = total_sum(list_a)
# 결과 출력
print("Sum of all elements in list_a: ", sum_list)

Sum of all elements in list_a:  4950



NumPy 배열 array_a의 형태를 reshape()를 이용하여 변환하고 array_b에 할당함.

In [7]:
array_b = array_a.reshape(5,20)
print(array_b)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


NumPy의 np.sum()함수를 이용하여 각각의 열 별로 합을 구함.

In [8]:
column_sum_array = np.sum(array_b, axis=0)
print("Column sum of array_b: ", column_sum_array)

Column sum of array_b:  [200 205 210 215 220 225 230 235 240 245 250 255 260 265 270 275 280 285
 290 295]


## 프로그래밍 문제 1-2: Python의 리스트 list_b 를 이용하여 위의 np.sum(array_b, axis=0)과 같은 계산을 수행하는 column_sum() 함수를 작성하시오.

NumPy의 array_b 배열을 Python의 기본 list_b 리스트로 변환

In [9]:
list_b = array_b.tolist()
print(list_b)

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39], [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59], [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79], [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]


In [10]:
"""
이 셀 안에 코드를 작성하시오.
"""
# 함수 작성
def column_sum(b):
    list_c = np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
    b = np.array(b)
    i = 0
    for row in list_b:
        i = 0
        for element in row:

            list_c[i] += element
            i+=1
    return list_c

위에 구현한 column_sum() 함수를 호출하여 반환된 결과값을 출력함.

In [11]:
# 함수 호출
column_sum_list = column_sum(list_b)
# 결과 출력
print("Column sum of list_b: ", column_sum_list)

Column sum of list_b:  [200 205 210 215 220 225 230 235 240 245 250 255 260 265 270 275 280 285
 290 295]


NumPy의 np.sum()함수를 이용하여 각각의 행 별로 합을 구함.

In [12]:
row_sum_array = np.sum(array_b, axis=1)
print("Row sum of array_b: ", row_sum_array)

Row sum of array_b:  [ 190  590  990 1390 1790]


## 프로그래밍 문제 1-3: Python의 리스트 list_b 를 이용하여 위의 np.sum(array_b, axis=1)과 같은 계산을 수행하는 row_sum() 함수를 작성하시오.

In [13]:
"""
이 셀 안에 코드를 작성하시오.
"""
# 함수 작성
def row_sum(b):
    list_c = np.array([0,0,0,0,0])
    b = np.array(b)
    i = 0
    for row in list_b:
        for element in row:

            list_c[i] += element
        i+=1
    return list_c

위에 구현한 row_sum() 함수를 호출하여 반환된 결과값을 출력함.

In [14]:
# 함수 호출
row_sum_list = row_sum(list_b)
# 결과 출력
print("Row sum of list_b: ", row_sum_list)

Row sum of list_b:  [ 190  590  990 1390 1790]


# 문제 2 (5 points)
## 아래 주어진 NumPy의 array_c와 array_d를 갖고 문제 1의 순서대로 NumPy배열을 리스트로 변환한 후 np.max()와 같은 계산을 수행하는 find_max(), find_column_max(), find_row_max() 세개의 함수를 작성하시오. np.max() 와 구현한 함수로 부터 얻은 결과값을 비교하시오.

In [15]:
array_c = np.arange(0,200)
print(array_c)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199]



## 프로그래밍 문제 2-1

In [16]:
max_array = np.max(array_c)
print("Maximum value in array_c: ", max_array)

Maximum value in array_c:  199


In [17]:
"""
이 셀 안에 코드를 작성하시오.
"""
# 함수 작성
def find_max(c):
    maxNum = 0
    c = np.array(c)
    for num in c:
        if num>maxNum:
            maxNum = num
    return maxNum

In [18]:
# NumPy배열에서 리스트로 변환
list_c = array_c.tolist()

In [19]:
# 리스트를 입력값으로 하는 find_max() 함수 호출하여 결과값을 출력
max_list = find_max(list_c)
print("Maximum value in list_c: ", max_list)

Maximum value in list_c:  199


## 프로그래밍 문제 2-2

In [20]:
array_d = array_c.reshape(20,10)
print(array_d)

[[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]]


In [21]:
column_max_array = np.max(array_d, axis=0)
print("Maximum value of each column in array_d: ", column_max_array)

Maximum value of each column in array_d:  [190 191 192 193 194 195 196 197 198 199]


In [ ]:
"""
이 셀 안에 코드를 작성하시오.
"""
# 함수 작성
def find_column_max(d):
    

In [ ]:
# NumPy배열에서 리스트로 변환
list_d = array_d.tolist()

In [ ]:
# 리스트를 입력값으로 하는 find_column_max() 함수 호출하여 결과값을 출력
column_max_list = find_column_max(list_d)
print("Maximum value of each column in list_d: ", column_max_list)

## 프로그래밍 문제 2-3

In [ ]:
row_max_array = np.max(array_d, axis=1)
print("Maximum value of each row in array_d: ", row_max_array)

In [ ]:
"""
이 셀 안에 코드를 작성하시오.
"""
# 함수 작성
def find_row_max(d):
    

In [ ]:
# 리스트를 입력값으로 하는 find_row_max() 함수 호출하여 결과값을 출력
row_max_list = find_row_max(list_d)
print("Maximum value of each row in list_d: ", row_max_list)

# 문제 3 (1 point)
## NumPy에서 제공되는 함수(예: np.sum(), np.max() )와 list를 이용하여 직접 구현한 함수 (total_sum(), column_sum(), row_sum(), find_max(), find_column_max(), find_row_max() )의 실행 속도를 측정하여 비교하시오. (보충 설명: 위 문제 1과 문제 2에서 각각의 함수가 호출되어 실행된 셀안에서 실행시간을 측정하시오.)
(참고: %time 명령을 이용하거나(option 1) 아래 코드를 참고해서(option 2) 실행시간을 측정하시오.)

In [ ]:
%time # option 1

print("")

import time # option 2
start = time.time()
# 코드 실행
print("hello")
end = time.time()
print(end - start)

### 함수들의 실행시간를 보고(report)하고 얻은 결과를 바탕으로 결론을 요약해서 작성하시오.
(Markdown 과 Code를 활용하여 자유형식으로 아래에 결론을 작성 (셀 추가 가능) )

실행 속도:

결론:
